{
 "title": "HAProxy Ingress",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(time() - haproxy_process_start_time_seconds)"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "count(haproxy_process_start_time_seconds)"
    }
   ]
  },
  {
   "title": "Frontend OK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count by (proxy) (haproxy_frontend_status == 1)",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Frontend FULL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by (proxy) (haproxy_frontend_status == 2) or vector(0)",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Frontend STOPPED",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "count by (proxy) (haproxy_frontend_status == 0 ) or vector(0)",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Backend DOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "count by (proxy) (haproxy_backend_status == 0) or vector(0)",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Connections and Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_process_current_connection_rate)",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(haproxy_process_current_session_rate)",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "SSL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_process_ssl_connections_total[5m]))",
     "legendFormat": "conns"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(haproxy_process_jobs)", "legendFormat": "jobs" }
   ]
  },
  {
   "title": "Request and Response Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_requests_denied_total[5m]))",
     "legendFormat": "Requests Denied"
    },
    {
     "expr": "sum(rate(haproxy_frontend_responses_denied_total[5m]))",
     "legendFormat": "Responses Denied"
    },
    {
     "expr": "sum(rate(haproxy_frontend_request_errors_total[5m]))",
     "legendFormat": "Request Error"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_process_current_tasks)",
     "legendFormat": "tasks"
    }
   ]
  },
  {
   "title": "Active and Connected Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_process_active_peers)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(haproxy_process_connected_peers)",
     "legendFormat": "Connected"
    }
   ]
  },
  {
   "title": "Process Run Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(haproxy_process_current_run_queue)",
     "legendFormat": "Queued"
    }
   ]
  },
  {
   "title": "Connection and Session Denied",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_denied_connections_total[5m]))",
     "legendFormat": "Connection Denied"
    },
    {
     "expr": "sum(rate(haproxy_frontend_denied_sessions_total[5m]))",
     "legendFormat": "Session Denied"
    }
   ]
  },
  {
   "title": "Frontend Bytes In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (proxy) (rate(haproxy_frontend_bytes_in_total[5m]))",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Frontend Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (proxy) (rate(haproxy_frontend_connections_total[5m]))",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Frontend Bytes Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (proxy) (rate(haproxy_frontend_bytes_out_total[5m]))",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "Frontend Requests (TCP and HTTP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (proxy)(rate(haproxy_frontend_connections_total[5m]))",
     "legendFormat": "{{proxy}}"
    }
   ]
  }
 ]
}